### ISSUE TITLE
xdg-mime: application argument missing

### ISSUE THREAD

**Issue by VERTlG0** [ZelCore-io/Zelcore#24]
All latest version down to 3.6.2 will not run on my Linux. Only 3.6.0 runs.  When trying the later versions the message 
" Try 'xdg-mime --help' for more information.  xdg-mime: application argument missing " is scrolled in the terminal and the app never opens up.

All version 3.6.4-beta-build-1907.appimage, 3.7.0-beta-build-1909.appimage, 3.7.1.Appimage, 3.7.2.-beta-build-1975.appimage, 3.8.0-beta-build-1988.appimage, and 3.9.0.Appimage all have this same issue. So not sure what was changed in 3.6.4 and up (3.6.2 runs but has a javascript error) but apparently they all have the same code added/changed that causes the app to not even open.. Again 3.6.0-beta-build-1869.appimage runs perfectly.   

If you like I can gdb with your assistance to target output to help identify the issue.

**Comment by TheTrunk** [comment]
Hi,
Thank you for reporting it. What is your operating system please? This is regarding AppImage right? Can you confirm if deb package is working correctly for you?

**Comment by VERTlG0** [comment]
Whoops sorry for the long delay and not including my distro.  Yes this is in regards to the Appimage.  
I just tried running ZelCore-3.10.0-beta-build-2048.AppImage as well and same issue. Just scrolls "xdg-mime --help for more information."

However, the latest versions of ZelCore.AppImage no longer have this problem. The newer versions however seem to take some time to run after issuing the command. Theres a long pause, but eventually the wallet window pops open. 

distro: Gentoo 64-bit
kernel: linux-5.10.16
cpu: intel i7 9700k
ram: 32GB
gfx card: Nvidia RTX 2080 Super
xdg: xdg-utils-1.1.3_p20200220-r1
