### ISSUE TITLE
AppImage very slow to launch

### ISSUE THREAD

**Issue by shmox75** [ZelCore-io/Zelcore#37]
Hi I am on opensuse tumbleweed, the AppImage is very slow to launch. More than one minute sometimes more than two minutes for the window to appear.

**Comment by TheTrunk** [comment]
Hi, we are targeting and building on Ubuntu 16+. Can you please tell us more specifics about your machine and precise system specifications?
Thank you for the update :+1:

**Comment by shmox75** [comment]
My distro is opensuse tumbleweed.
Here is my uname -a
`Linux localhost.localdomain 5.11.11-1-default #1 SMP Tue Mar 30 17:57:52 UTC 2021 (dbc4a02) x86_64 x86_64 x86_64 GNU/Linux`

If I launch the AppImage in termianl I get this error:
`/usr/bin/AppImageLauncher: /usr/lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)`

**Comment by shmox75** [comment]
Hi, it's me again, since (unfortunately) you are only supporting ubuntu for linux, may I ask you if I can run zelcore in a virtual machine ? thanks again

**Comment by TheTrunk** [comment]
Hi, yes you can, although at performance penalty as of the virtualisation

**Comment by shmox75** [comment]
> Hi, yes you can, although at performance penalty as of the virtualisation

Okay, thank you, wish you'll have more distro builds :)

**Comment by 9-** [comment]
![image](https://user-images.githubusercontent.com/5953183/124788743-d902bb00-df73-11eb-89c1-afc9689c8e85.png)
Hi, it is very slow for me to start zelcore on normal desktop user (taking more than 15 minutes!). If I run as root it's really fast.
Process inspection told me that it runs xdg-settings set default-url-scheme-handler countless times (probably the number of tokens supported on zelcore) and it is very slow.

**Comment by jfamousket** [comment]
+1 for slow launch, I am on arch linux too.
I created an aur package by the way for arch users https://aur.archlinux.org/packages/zelcore/

**Comment by archit3kt** [comment]
Same issue here for KDE manjaro, please do something about it. @jfamousket please see my comment on your AUR package

**Comment by dramirezRT** [comment]
Hi, same issue here with Arch Linux. :(
