### ISSUE TITLE
Zelcore App

### ISSUE THREAD

**Issue by olivero09** [ZelCore-io/Zelcore#44]
Transferred some Kadena from Kucoin to your app (Kadena wallet) it has been 30min nothing has been arrived yet. No help is given, your live chat not working. Anyone here who can help?

**Comment by olivero09** [comment]
> Transferred some Kadena from Kucoin to your app (Kadena wallet) it has been 30min nothing has been arrived yet. No help is given, your live chat not working. Anyone here who can help?

I received it on Chain ID 1 why was this the case? Is that standard? Why wouldn't it arrive on Chain ID 0 as this is what was it set to. Thx

**Comment by TheTrunk** [comment]
Some services operate only on specific kadena chain ids. Kucoin only uses chain id 1 for example.
